version: '3.6'

services:
  my-app2:
    image: nginx
    restart: always
    volumes:
      - "./:/usr/share/nginx/html"
    environment:
      - VIRTUAL_HOST=website2.com 
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=website2.com 
      - LETSENCRYPT_EMAIL=email@website2.com 
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
